Drive time
joshsoftware/OnCoT-API pull request #12
Opened 2021-02-27 17:56 UTC by atirabagwan

drive start time left

2021-02-28 03:33 UTC, rahulknojha requested changes
After multiple feedbacks  I can still see following issues.
 - End of new line is missing in one file
 - Still I can see files committed under test folder. 
 
Apart from these. Please add rspec test cases for changes you have made.

2021-02-28 03:33 UTC, rahulknojha commented on app/controllers/drives_controller.rb
> +      render json: { message: 'drive already started' }
what will be status of HTTP response here 200 ?

2021-02-28 03:33 UTC, rahulknojha commented on app/controllers/drives_controller.rb
> +      render json: { time_left: time_left }
Add two methods in ApiController say `render_success` and `render_error`, so that we don't need to repeat render json: '', and http status

Signature of methods will be something like this.

```
  def render_success(data: nil, message: nil)
  end
  
  def render_error(message: nil)
  end
```

2021-03-01 06:29 UTC, rahulknojha commented on config/routes.rb
> +  get '/drive/:id', to: "drives#drive_time_left"
```
resources :drives do
     get :drive_time_left, on: :member
end
```

2021-03-18 06:26 UTC, rahulknojha requested changes

2021-03-18 06:26 UTC, rahulknojha commented on app/controllers/candidates_controller.rb
> +      render_success(data: { time_left: time_left }, message: I18n.t('test.time_remaining'), status: 200)
In above two render_success statement only message is changing so can we make only message condition instead of entire statement. 

```
 
```

2021-03-18 06:26 UTC, rahulknojha commented on app/controllers/candidates_controller.rb
> +    # byebug
what is this ?

2021-03-18 06:26 UTC, rahulknojha commented on app/controllers/candidates_controller.rb
> +    @duration = @drive.duration if @drive
this can be written as

```
@duration = @drive&.duration
```

2021-03-18 06:26 UTC, rahulknojha commented on app/controllers/candidates_controller.rb
> +    return unless candidate.update(candidate_params)
this has been discussed in earlier PR as well, what it is going to return to the client in case of failure ? 

Self review missing

2021-03-18 06:26 UTC, rahulknojha commented on app/controllers/drives_controller.rb
> +      render_success(data: @time_left_to_start, message: I18n.t('drive.yet_to_start'), status: 200)
Here as well data and msg is only conditional not entire statement,

2021-03-18 06:26 UTC, rahulknojha commented on app/controllers/drives_controller.rb
> +        render_success(data: @time_left_already_stated, message: I18n.t('drive.ended'),
do we need to send status explicitly I guess it should be default status

2021-03-18 06:26 UTC, rahulknojha commented on app/controllers/drives_controller.rb
> +      if @time_left_already_stated.positive?
started ?

2021-03-18 06:26 UTC, rahulknojha commented on app/controllers/drives_controller.rb
> +    @current_time = DateTime.now.localtime
do we need all above three variables as instance variable ?

2021-03-18 06:26 UTC, rahulknojha commented on config/database.yml
> +  password:
avoid un intentional commit.

2021-03-18 06:26 UTC, rahulknojha commented on spec/request/candidates_spec.rb
> +  describe 'candidate test time' do
it should mention action name

2021-03-18 06:26 UTC, rahulknojha commented on spec/request/candidates_spec.rb
> +    end
add test cases for negative scenario like first name is not present.

2021-03-18 06:26 UTC, rahulknojha commented on spec/request/drives_spec.rb
> +# frozen_string_literal: true
why we are writing request specs here ?, we are using controller spec right then move it to controller folder

2021-03-18 07:06 UTC, varungadde99 commented on spec/request/drives_spec.rb
> +# frozen_string_literal: true
Moved the _specs.rb files to app/controllers folder post discussion.

2021-03-18 07:06 UTC, varungadde99 commented on config/database.yml
> +  password:
file post merge added to .gitignore.

2021-03-18 07:48 UTC, varungadde99 commented on app/controllers/candidates_controller.rb
> +    return unless candidate.update(candidate_params)
Added render_error in the else scenario where due to wrong params the update can fail.

2021-03-18 11:34 UTC, varungadde99 commented on spec/request/candidates_spec.rb
> +    end
Pending for discussion.

2021-03-18 11:57 UTC, varungadde99 commented on config/database.yml
> +  password:
Sir still the file is added to .gitignore, still its not resolving this error.

2021-03-22 11:33 UTC, rahulknojha approved these changes

2021-03-22 12:03 UTC, merged