Problem API Added
joshsoftware/OnCoT-API pull request #15
Opened 2021-03-02 10:25 UTC by samu80

2021-03-02 12:39 UTC, vaibhav8186 commented on app/controllers/api_controller.rb
> +    render json: { message: message, data: data }, status: 200
@samu80   In response sequence should be first data then message.

2021-03-02 12:44 UTC, vaibhav8186 commented on app/controllers/problems_controller.rb
> +    problem = Problem.find(params[:id])
@samu80   find gives an exception in the case record not found. Can we use `find_by_id` here?

2021-03-02 12:45 UTC, vaibhav8186 commented on spec/request/problems_spec.rb
> +    @organization = FactoryBot.create(:organization)
@samu80   can we use only create method here to create test data. Every time use `FactoryBot` class increase redundant code.

2021-03-02 12:47 UTC, vaibhav8186 commented on spec/request/problems_spec.rb
> +    expect(JSON.parse(response.body).size).to eq(2)
@samu80 It's better to give on an empty line after your API call. and instead of expecting count can we check exact data here.

2021-03-02 12:48 UTC, vaibhav8186 requested changes
Added comments.

2021-03-03 03:09 UTC, samu80 commented on app/controllers/api_controller.rb
> +    render json: { message: message, data: data }, status: 200
okay

2021-03-03 03:10 UTC, samu80 commented on spec/request/problems_spec.rb
> +    @organization = FactoryBot.create(:organization)
okay

2021-03-03 05:34 UTC, vaibhav8186 commented on spec/request/problems_spec.rb
> +    @expected = {
@samu80  No need to add instance variable here. You can add two expect statements here. one for data and another for the message.

2021-03-12 12:27 UTC, closed without merging