code run api and unit testing added
joshsoftware/OnCoT-API pull request #18
Opened 2021-03-04 05:56 UTC by Sumit-Dhandale

api for code execution is added
unit testing external api using webmock added

2021-03-11 08:25 UTC, rahulknojha requested changes

2021-03-11 08:25 UTC, rahulknojha commented on app/services/judge_zero_api.rb
> +  BASE_URI = 'http://roupi.xyz'
You should store this value in env, you can use Figaro , or credentials.yml for storing this

2021-03-11 08:25 UTC, rahulknojha commented on config/routes.rb
> +  get '/submission/:token', to: 'executions#submission_status'
use rails new conventions to define routes,

2021-03-11 08:25 UTC, rahulknojha commented on app/controllers/executions_controller.rb
> +class ExecutionsController < ApplicationController
controller structure should be api::v1::your_controller, why this is inherited from application controller ?

2021-03-11 08:25 UTC, rahulknojha commented on app/controllers/executions_controller.rb
> +    render json: { token: @token }
use helper methods defined in API controller for rendering

2021-03-11 08:25 UTC, rahulknojha commented on app/controllers/executions_controller.rb
> +    @token = JSON.parse(response.body)['token']
not sure why instance variable is needed here ?

2021-03-11 08:25 UTC, rahulknojha commented on spec/spec_helper.rb
> +  end
why you are stubbing in rails helper ? why not in individual files ?

2021-03-16 05:48 UTC, vaibhav8186 requested changes

2021-03-16 05:48 UTC, vaibhav8186 commented on app/controllers/executions_controller.rb
> +      render_error(message: I18n.t(body['error']), status: :not_found)
@Sumit-Dhandale  ` body['error']`  is this not defined in your en.yml?

2021-03-16 05:48 UTC, vaibhav8186 commented on spec/requests/executions_request_spec.rb
> +    it 'returns http success' do
@Sumit-Dhandale  Empty line missing here.

2021-03-16 05:48 UTC, vaibhav8186 commented on spec/requests/executions_request_spec.rb
> +  describe 'GET /executions/:token/submission_status' do
@Sumit-Dhandale  `describe` block will not contain your routes. Please take a look at what should write to `describe` block.

2021-03-16 05:48 UTC, vaibhav8186 commented on spec/requests/executions_request_spec.rb
> +      body = JSON.parse(response.body)
@Sumit-Dhandale   use the `json_resonse` method from request helper.

2021-03-17 09:22 UTC, vaibhav8186 requested changes

2021-03-17 09:22 UTC, vaibhav8186 commented on app/controllers/executions_controller.rb
> +    if body['error']
@Sumit-Dhandale  can we check if we are getting success from this API call.

2021-03-17 09:22 UTC, vaibhav8186 commented on app/controllers/executions_controller.rb
> +    headers = { "Content-Type": 'application/json' }
@Sumit-Dhandale  If headers are the same to be used throughout the application then it will be better to declare where we have used to call JudgeZeroApi class. i.e   In `app/services/judge_zero_api.rb `

2021-03-22 11:25 UTC, vaibhav8186 approved these changes

2021-03-22 11:27 UTC, rahulknojha commented on config/application.rb
> +      if File.exist?(env_file)
can we use figaro gem here ?

2021-03-22 11:28 UTC, rahulknojha commented on app/controllers/executions_controller.rb
> +    body = JSON.parse(response.body)
can we parse response in service to avoid  repetition of code ?

2021-04-08 10:20 UTC, closed without merging