Feature/drive details api
joshsoftware/OnCoT-API pull request #20
Opened 2021-03-06 22:41 UTC by Sumit-Dhandale

Drive details API

2021-04-07 05:38 UTC, rahulknojha requested changes

2021-04-07 05:38 UTC, rahulknojha commented on app/controllers/api/v1/drives_controller.rb
> +        render_success(data: drive, message: I18n.t('ok.message'))
we are not using serializer here ?
For the sake consistency  can we follow same pattern ?

2021-04-07 05:38 UTC, rahulknojha commented on app/controllers/api/v1/drives_controller.rb
> +        return render_error(message: I18n.t('token_not_found.message'), status: :not_found) unless drives_candidate
can we simply use find, so the the global exception handler will handle this by default

2021-04-07 05:38 UTC, rahulknojha commented on spec/controllers/api/v1/drives_controller_spec.rb
> +        expect(response.body).to eq('token is not present')
har coded string, use translation

2021-04-07 06:14 UTC, somnath77 commented on app/controllers/api/v1/drives_controller.rb
> +        render_success(data: drive, message: I18n.t('ok.message'))
Used serializer

2021-04-07 06:14 UTC, somnath77 commented on app/controllers/api/v1/drives_controller.rb
> +        return render_error(message: I18n.t('token_not_found.message'), status: :not_found) unless drives_candidate
Finding by token, which is not primary key

2021-04-07 06:14 UTC, somnath77 commented on spec/controllers/api/v1/drives_controller_spec.rb
> +        expect(response.body).to eq('token is not present')
used translation

2021-04-07 06:15 UTC, vaibhav8186 requested changes

2021-04-07 06:15 UTC, vaibhav8186 commented on spec/controllers/api/v1/drives_controller_spec.rb
> +        expect(response.body).to eq('Record not found')
@Sumit-Dhandale   use translation here.

2021-04-07 06:15 UTC, vaibhav8186 commented on app/controllers/api/v1/drives_controller.rb
> +        drives_candidate = DrivesCandidate.find_by(token: params[:id])
@Sumit-Dhandale  we can use active records association here. If we have `drive has many drive_candidates`. Then we can use `drive.drives_candidates.where()`  . It increases the readability of your code as well.

2021-04-07 06:52 UTC, somnath77 commented on app/controllers/api/v1/drives_controller.rb
> +        drives_candidate = DrivesCandidate.find_by(token: params[:id])
It's not possible as we have to find drive details only by using token

2021-04-07 06:52 UTC, somnath77 commented on spec/controllers/api/v1/drives_controller_spec.rb
> +        expect(response.body).to eq('Record not found')
Done

2021-04-07 06:58 UTC, varungadde99 approved these changes

2021-04-07 11:41 UTC, varungadde99 approved these changes

2021-04-08 04:44 UTC, vaibhav8186 requested changes

2021-04-08 04:44 UTC, vaibhav8186 commented on config/locales/en.yml
> +    message: "token is not present"
@Sumit-Dhandale  Please do proper formating here.` "Token is Not Present"`. Apply this change other place as well.

2021-04-08 04:58 UTC, somnath77 commented on config/locales/en.yml
> +    message: "token is not present"
Changes added

2021-04-08 05:34 UTC, vaibhav8186 requested changes

2021-04-08 05:34 UTC, vaibhav8186 commented on config/locales/en.yml
> +      message: "Dubmission Not Created"
wrong spelling

2021-04-08 05:39 UTC, vaibhav8186 approved these changes

2021-04-08 09:41 UTC, rahulknojha approved these changes

2021-04-08 09:46 UTC, merged