Feature/candidate invitaition
joshsoftware/OnCoT-API pull request #21
Opened 2021-03-07 11:47 UTC by Sumit-Dhandale

invitation link to candidate via mail

2021-03-22 11:39 UTC, rahulknojha requested changes

2021-03-22 11:39 UTC, rahulknojha commented on app/controllers/candidates_controller.rb
> +      rescue StandardError => e
what kind of exception will occur here ? Can you please elaborate ?

2021-03-22 11:39 UTC, rahulknojha commented on app/mailers/candidate_mailer.rb
> +    mail(to: user.email, from: ENV['MAIL_USERNAME'], subject: 'Invitation for coding round',
subject needs to be proper, should include organisation name as well

2021-03-22 11:39 UTC, rahulknojha commented on app/models/drives_candidate.rb
> +    save!
what if it raises an exception ?

2021-03-22 11:39 UTC, rahulknojha commented on config/application.rb
> +      env_file = File.join(Rails.root, 'config', 'local_env.yml')
please update as discussed in other PR

2021-03-22 11:39 UTC, rahulknojha commented on spec/controllers/candidates_controller_spec.rb
> +    expect { CandidateMailer.invitation_email(user, drive_candidate).deliver_now }.to change {
you are writing test cases for controller but you have not called the controller action, and manually repeating the code here. I m not sure what you are trying to test here

2021-04-06 04:56 UTC, somnath77 commented on app/models/drives_candidate.rb
> +    save!
handled exception

2021-04-06 04:56 UTC, somnath77 commented on spec/controllers/candidates_controller_spec.rb
> +    expect { CandidateMailer.invitation_email(user, drive_candidate).deliver_now }.to change {
Added corrected unit tests

2021-04-06 04:56 UTC, somnath77 commented on app/mailers/candidate_mailer.rb
> +    mail(to: user.email, from: ENV['MAIL_USERNAME'], subject: 'Invitation for coding round',
Added detailed subject

2021-04-06 04:57 UTC, somnath77 commented on app/controllers/candidates_controller.rb
> +      rescue StandardError => e
handled specific exceptions

2021-04-06 04:58 UTC, rahulknojha commented on app/models/drives_candidate.rb
> +      raise e if drives_candidate.nil?
how this can be nil ? what will be the scenario ?

2021-04-06 07:24 UTC, rahulknojha submitted a review, later dismissed

2021-04-07 04:46 UTC, rahulknojha approved these changes

2021-04-07 04:50 UTC, merged