Admin Problems CRUD
joshsoftware/OnCoT-API pull request #24
Opened 2021-03-09 12:00 UTC by somnath77

Created ProblemController with CRUD operations on problems, unit tests for it. Used serialization, I18n

2021-03-09 14:23 UTC, rahulknojha requested changes
Added Few comments , I have not reviewed all, Please refer comments on @varungadde99  PR and if you find any similarity please fix then I will resume my review.

2021-03-09 14:23 UTC, rahulknojha commented on app/controllers/api/v1/admin/problems_controller.rb
> +      render_success(data: {problem:  problem}, message: I18n.t('create.success', model_name: Problem))
use serializer, whenever you have to render a object or collection of object, @varungadde99 Please help here.

2021-03-09 14:23 UTC, rahulknojha commented on app/controllers/api/v1/admin/problems_controller.rb
> +      render_error(message:problem.errors.full_messages)
linting issue

2021-03-09 14:23 UTC, rahulknojha commented on app/controllers/api/v1/admin/problems_controller.rb
> +      render_error(message:'Problems not exist')
Please use translation, instead of hardcoded string,

2021-03-09 14:23 UTC, rahulknojha commented on app/controllers/api/v1/admin/problems_controller.rb
> +  def destroy
do we have destroy feature ?

2021-03-09 14:23 UTC, rahulknojha commented on app/controllers/api/v1/admin/problems_controller.rb
> +end
new line missing at EOF .

2021-03-09 14:23 UTC, rahulknojha commented on app/serializers/problem_serializer.rb
> +class ProblemSerializer < ActiveModel::Serializer
you have created serializer but not used ? 🤣

2021-03-09 14:23 UTC, rahulknojha commented on config/routes.rb
> +  		end
seems copy paste, @varungadde99  and @somnath77 you both have made same mistake in same file. 🤣

2021-03-09 14:23 UTC, rahulknojha commented on spec/factories/role.rb
> +    type { 'admin' }
type is a reserved keyword

2021-03-09 20:15 UTC, somnath77 commented on app/controllers/api/v1/admin/problems_controller.rb
> +      render_success(data: {problem:  problem}, message: I18n.t('create.success', model_name: Problem))
Used serializer

2021-03-09 20:17 UTC, somnath77 commented on app/controllers/api/v1/admin/problems_controller.rb
> +  def destroy
To delete a problem from problems set, we have a destroy feature

2021-03-09 20:17 UTC, somnath77 commented on app/controllers/api/v1/admin/problems_controller.rb
> +end
Added

2021-03-09 20:18 UTC, somnath77 commented on app/serializers/problem_serializer.rb
> +class ProblemSerializer < ActiveModel::Serializer
I had used but it was showing errors, so I removed serializer and committed code, but now I used serializer

2021-03-10 05:48 UTC, rahulknojha commented on spec/rails_helper.rb
> +def parseJson(obj)
naming convention is wrong

2021-03-10 05:48 UTC, rahulknojha commented on spec/rails_helper.rb
> +  problem_data = JSON.parse(obj)
how it can be problem only, it can be used in any spec right ?

2021-03-11 07:57 UTC, rahulknojha requested changes

2021-03-11 07:57 UTC, rahulknojha commented on app/controllers/api/v1/admin/problems_controller.rb
> +          problem = Problem.get_problem(id)
why this get_method is needed ? we already have find and find_by method.

2021-03-11 07:57 UTC, rahulknojha commented on app/controllers/api/v1/admin/problems_controller.rb
> +          problems = Problem.all
what if problems size is in thousands/lakhs/crs, will not it be difficult for client to handle it ?

2021-03-11 07:57 UTC, rahulknojha commented on spec/request/problems_spec.rb
> +           params: { title: 'a', description: 'b', created_at: Time.now, updated_at: Time.now, created_by_id: user.id,
Do you need to send created at and updated at ?, created_by_id also should be taken from session.

2021-03-11 07:57 UTC, rahulknojha commented on spec/request/problems_spec.rb
> +      expect(problem['data']['problem']['title']).to eq('b')
better way of testing change.

https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/change-matcher

2021-03-11 07:57 UTC, rahulknojha commented on spec/request/problems_spec.rb
> +      expect(response).to have_http_status(:ok)
also test that you are getting right problem

2021-03-11 07:57 UTC, rahulknojha commented on spec/request/problems_spec.rb
> +      expect(response).to have_http_status(:ok)
test for data count as well

2021-03-11 07:57 UTC, rahulknojha commented on spec/support/request_helpers.rb
> +    def json(response)
don't need to pass response, it should be available

2021-03-11 07:57 UTC, rahulknojha commented on app/controllers/api/v1/admin/problems_controller.rb
> +          if problem
As spoken earlier, no need to handle if else , if you can rescue exception globally and render not found, i.e 404.

2021-03-15 17:06 UTC, rahulknojha requested changes

2021-03-15 17:06 UTC, rahulknojha commented on app/controllers/api/v1/admin/problems_controller.rb
> +            render_error(message: I18n.t('index.error', model_name: Problem), status: 400)
what will be error in index ?

2021-03-15 17:06 UTC, rahulknojha commented on app/controllers/api/v1/admin/problems_controller.rb
> +            render_error(message: I18n.t('create.error', model_name: Problem), status: 400)
render specific error messages, like field cant be blank, you will get it from problem.erros.messages

2021-03-15 17:06 UTC, rahulknojha commented on spec/factories/role.rb
> +    updated_at { Time.now }
?????

2021-03-15 17:06 UTC, rahulknojha commented on spec/request/problems_spec.rb
> +      expect(response).to have_http_status(400)
check for particular error messages as well

2021-03-15 18:35 UTC, somnath77 commented on spec/factories/role.rb
> +    updated_at { Time.now }
Forgot to delete, deleted now

2021-03-15 18:36 UTC, somnath77 commented on app/controllers/api/v1/admin/problems_controller.rb
> +            render_error(message: I18n.t('create.error', model_name: Problem), status: 400)
Done

2021-03-15 18:36 UTC, somnath77 commented on app/controllers/api/v1/admin/problems_controller.rb
> +            render_error(message: I18n.t('index.error', model_name: Problem), status: 400)
No need of else part here, removed

2021-03-15 18:37 UTC, somnath77 commented on spec/request/problems_spec.rb
> +      expect(response).to have_http_status(400)
Added one expect to check correct error message

2021-03-16 05:36 UTC, rahulknojha commented on spec/request/problems_spec.rb
> +            params: { id: problem.id, title: 'b', description: 'b',
as this is not slow stopper, but giving name like a and b, c is not recommended. you can use Faker.

2021-03-16 05:37 UTC, rahulknojha submitted a review, later dismissed

2021-03-18 06:06 UTC, rahulknojha commented on config/locales/en.yml
> +  #   error: "Error in deleting %{model_name}"
do we need commented code here ?

2021-03-18 06:07 UTC, merged