Admin reviewer
joshsoftware/OnCoT-API pull request #25
Opened 2021-03-09 12:01 UTC by varungadde99

Admin - Reviewer Backend PR

    Added CRUD operations
    Added Serializer gem and functionality
    Added I18n Messages with interpolation of methods
    RSpec Unit Test for Reviewer CRUD

Please review and let me know the feedback.
Thanks.

2021-03-09 13:47 UTC, rahulknojha commented
> Please review and let me know the feedback.

A good example of how a PR description should be. 👍  

cc: @Sumit-Dhandale @samu80 @somnath77

2021-03-09 14:04 UTC, rahulknojha requested changes

2021-03-09 14:04 UTC, rahulknojha commented on test/controllers/api/v1/admin/reviewers_controller_test.rb
> +end
this is not needed, you can delete this as we are using rspec.

2021-03-09 14:04 UTC, rahulknojha commented on app/controllers/api/v1/admin/reviewers_controller.rb
> +    @user = User.find_by_id(params[:id])
use find and if not found it will raise an exception.

then catch not found exception in API controller and render 404 with not found message. this way you will get rid of handling if condition for find_by across the controller actions

2021-03-10 05:09 UTC, varungadde99 commented on app/controllers/api/v1/admin/reviewers_controller.rb
> +    if @user.update(user_params)
Added the else part as well. But while testing on Postman the else part is not rendered. It is returning 
"status": 500,
"error": "Internal Server Error",
 "exception": "#<NoMethodError: undefined method `destroy' for nil:NilClass>",

2021-03-10 05:10 UTC, varungadde99 commented on spec/request/reviewers_spec.rb
> +      parsed_json_data = JSON.parse(response.body)
I am facing issues while writing the helper method. Will require your assistance.

2021-03-10 05:10 UTC, varungadde99 commented on app/controllers/api/v1/admin/reviewers_controller.rb
> +  def destroy
A reviewer can be deleted from a global db of reviewers. So a delete functionality is required as well according to me.

2021-03-10 06:04 UTC, varungadde99 commented on app/controllers/api/v1/admin/reviewers_controller.rb
> +    role = Role.where(name: 'reviewer').first
Sir need discussion on this. Concept is not clear to me.

2021-03-10 12:06 UTC, varungadde99 commented on app/controllers/api/v1/admin/reviewers_controller.rb
> +    role = Role.where(name: 'reviewer').first
Done. Added Scope.

2021-03-10 12:07 UTC, varungadde99 commented on app/controllers/api/v1/admin/reviewers_controller.rb
> +  def destroy
Added the error_render_method in api_controller.rb - But on Postman testing the response message is not being rendered.

2021-03-10 12:08 UTC, varungadde99 commented on app/controllers/api/v1/admin/reviewers_controller.rb
> +    if @user.update(user_params)
Added the code for Exception Rescue.

2021-03-10 12:09 UTC, varungadde99 commented on spec/request/reviewers_spec.rb
> +      parsed_json_data = JSON.parse(response.body)
Added the json helper function in the spec/support/request_helpers.rb

2021-03-10 12:30 UTC, varungadde99 commented
Codacy is highlighting the - Brakeman Warning
https://stackoverflow.com/questions/40778760/what-is-this-unscoped-call-to-warning-in-brakeman
Need discussion over find() and un-scoped call.

2021-03-11 08:10 UTC, rahulknojha requested changes

2021-03-11 08:10 UTC, rahulknojha commented on app/controllers/api/v1/admin/reviewers_controller.rb
> +          @users = User.where(role: role)
why do  you need instance variable here ? check for other places as well ?

above two statement can be combined in one.
```
users = User.joins(:role).where(roles: { name: 'reviewer' }) 
```

2021-03-11 08:10 UTC, rahulknojha commented on app/controllers/api/v1/admin/reviewers_controller.rb
> +          return unless @user.save
what will be message to client , if used doesn't get saved ? check for other places as well where ever you followed same approach.

2021-03-11 08:10 UTC, rahulknojha commented on app/controllers/api/v1/admin/reviewers_controller.rb
> +                         message: I18n.t('create.success', model_name: 'Reviewer'), status: 201)
201 eq to :created

2021-03-11 08:10 UTC, rahulknojha commented on app/controllers/api/v1/admin/reviewers_controller.rb
> +        end
destroy still valid ?

2021-03-11 08:10 UTC, rahulknojha commented on app/controllers/api_controller.rb
> +  rescue_from ActiveRecord::RecordNotFound, with: :error_render_method
move this line to top

2021-03-11 08:10 UTC, rahulknojha commented on app/controllers/api_controller.rb
> +    render_error(message: 'Record not found')
status should be 404

2021-03-11 08:10 UTC, rahulknojha commented on config/database.yml
> +  password:
this should not be commited

2021-03-11 08:10 UTC, rahulknojha commented on spec/request/reviewers_spec.rb
> +      created_reviewer = create(:reviewer)
varibale should be `reviewer` only

2021-03-11 08:10 UTC, rahulknojha commented on spec/request/reviewers_spec.rb
> +      expect(parsed_json_data['data']['user']['first_name']).to eq(params[:first_name])
better to use this while testing change 

https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/change-matcher

2021-03-11 08:10 UTC, rahulknojha commented on spec/request/reviewers_spec.rb
> +      params_to_be_updated = {
only `params` is fine

2021-03-11 09:10 UTC, varungadde99 commented on app/controllers/api/v1/admin/reviewers_controller.rb
> +          return unless @user.save
Only case of create we need to give back message. Other places the Rescue function will render is user doesn't exists.

2021-03-11 09:18 UTC, varungadde99 commented on spec/request/reviewers_spec.rb
> +      expect(parsed_json_data['data']['user']['first_name']).to eq(params[:first_name])
There is no change in the expect() statement. I am just checking whether the respone.body returns the same details after created a reviewer object as the params details. Please let me know if anything is to be done regarding the same.

2021-03-15 17:10 UTC, rahulknojha commented
Move coverage folder to git ignore and resolve conflicts, after that I will resume review

2021-03-16 10:12 UTC, vaibhav8186 requested changes

2021-03-16 10:12 UTC, vaibhav8186 commented on config/locales/en.yml
> +    failed: "%{model_name} couldn't be created successfully."
@varungadde99  change message  -> Unable to create "%{model_name}

2021-03-16 10:12 UTC, vaibhav8186 commented on config/locales/en.yml
> +    failed: "Particular %{model_name} couldn't be found."
"Unable to update %{model_name}"  @varungadde99  update other places as well.

2021-03-19 09:36 UTC, merged