Candidate update and problem display api
joshsoftware/OnCoT-API pull request #28
Opened 2021-03-11 11:38 UTC by samu80

Contains API for 
    1)update candidate details 
    2)display the problem with title, description, submission count.
with RSpec unit testing

2021-03-11 11:51 UTC, rahulknojha requested changes

2021-03-11 11:51 UTC, rahulknojha commented on app/controllers/candidates_controller.rb
> +    candidate = Candidate.find_by(id: @drive_candidate.candidate_id)
it should be written like, candidate = @drive_candidate.candidate

2021-03-11 11:51 UTC, rahulknojha commented on app/controllers/candidates_controller.rb
>      if candidate.update(candidate_params)
what if candidate not found ?

2021-03-11 11:51 UTC, rahulknojha commented on app/controllers/problems_controller.rb
> +  def display
any specific reason behind using display instead of show ?

2021-03-11 11:51 UTC, rahulknojha commented on app/controllers/problems_controller.rb
> +    problem = Problem.find_by(drive_id: params[:id])
as we have already handled exception , can we use find instead of find by ?

after doing this we may not need to handle if and else part

2021-03-11 11:51 UTC, rahulknojha commented on db/migrate/20210308063125_add_drive_id_to_problems.rb
> +    add_column :problems, :drive_id, :integer
why we are adding drive id to problem, won't a problem belong to multiple drive ?

2021-03-11 11:51 UTC, rahulknojha commented on spec/factories/drives_problem.rb
> +    updated_at { Time.now }
this is added by default, no need to set it explicitly

2021-03-11 11:51 UTC, rahulknojha commented on spec/models/test_case_spec.rb
> +    no_problem_testcase = TestCase.new(problem: nil)
I think this has been said earlier too , instead of `TestCase.new(problem: nil)` we can use facoty methods like `build(:test_case, problem: nil)`

2021-03-11 11:51 UTC, rahulknojha commented on spec/models/test_case_spec.rb
> +    no_problem_testcase.should_not be_valid
avoid using `should` matcher use latest syntax.
`expect(no_problem_testcase).to be_invalid`

Read more about this.

https://www.betterspecs.org/#expect

2021-03-11 11:51 UTC, rahulknojha commented on spec/request/candidates_spec.rb
> +      patch :update, params: { id: Faker::Number }
👍 Good

2021-03-11 11:51 UTC, rahulknojha commented on spec/request/problems_spec.rb
> +  context 'problem#show' do
see betterspecs site or talk to @varungadde99 and @somnath77  regarding structure of test cases, Also I don't see problem#show action in controller

2021-03-11 13:33 UTC, samu80 commented on app/controllers/problems_controller.rb
> +  def display
In Admin side problem CRUD ,show also will be there so for avoiding conflicts I changed show with display method

2021-03-11 13:44 UTC, samu80 commented on app/controllers/problems_controller.rb
> +    problem = Problem.find_by(drive_id: params[:id])
find method uses primary key for finding data, but here we are finding data with drive_id so can't use find method

2021-03-11 14:14 UTC, samu80 commented on db/migrate/20210308063125_add_drive_id_to_problems.rb
> +    add_column :problems, :drive_id, :integer
Yes, dropped column drive_id from problem table

2021-03-11 15:10 UTC, rahulknojha requested changes

2021-03-11 15:10 UTC, rahulknojha commented on app/controllers/candidates_controller.rb
> +      render_error(message: I18n.t('not_found.message'))
what will be status in case of not found

2021-03-11 15:10 UTC, rahulknojha commented on app/controllers/problems_controller.rb
> +  def display
@samu80 , can you explain a little bit more how conflict will occur ?

2021-03-11 15:10 UTC, rahulknojha commented on app/controllers/problems_controller.rb
> +    id = params[:id].to_s
not needed

2021-03-11 15:10 UTC, rahulknojha commented on db/migrate/20210308063125_add_drive_id_to_problems.rb
> +    add_column :problems, :drive_id, :integer
Remove both migrations now, as they have no meaning now.

2021-03-11 15:10 UTC, rahulknojha commented on spec/request/problems_spec.rb
> +RSpec.describe ProblemsController, type: :controller do
see betterspecs site or talk to @varungadde99 and @somnath77 regarding structure of test cases, Also I don't see problem#show action in controller

2021-03-12 05:34 UTC, samu80 commented on app/controllers/problems_controller.rb
> +  def display
here I am finding problem from DrivesProblem table , but in show method problem will be find with primary key its id so, conflict will occur

2021-03-15 06:56 UTC, rahulknojha commented on spec/request/problems_spec.rb
> +RSpec.describe ProblemsController, type: :controller do
update as discussed

2021-03-15 06:56 UTC, rahulknojha commented on app/controllers/problems_controller.rb
> +  def display
update as discussed

2021-03-15 06:56 UTC, rahulknojha submitted a review, later dismissed

2021-03-15 08:09 UTC, samu80 commented on app/controllers/problems_controller.rb
> +  def display
okay

2021-03-15 09:32 UTC, rahulknojha commented on .overcommit.yml
> +gemfile: Gemfile
why this change is needed ?

2021-03-15 09:33 UTC, rahulknojha commented on app/controllers/problems_controller.rb
> +  def show
we decided to make it index, now its show can you let me know why ?

2021-03-15 09:50 UTC, rahulknojha requested changes

2021-03-15 09:50 UTC, rahulknojha commented on spec/request/candidates_spec.rb
> +    context 'testing with correct id' do
no need to write `testing`, while writing test case it is understood that it is being tested,

2021-03-15 09:50 UTC, rahulknojha commented on spec/request/candidates_spec.rb
> +    context 'testing with random id which is not present in database' do
same as above

2021-03-15 10:07 UTC, samu80 commented on .overcommit.yml
> +gemfile: Gemfile
Actually not needed, so removed that line

2021-03-15 10:09 UTC, rahulknojha commented on config/routes.rb
> +  get '/drives/:id/problem' => 'problems#index'
do we need this ?

why can't we do like ?
```
  resources :drives do
     resources :problems, only: [:index]
  end
```

2021-03-15 10:20 UTC, samu80 commented on config/routes.rb
> +  get '/drives/:id/problem' => 'problems#index'
I have tried for this also, but that is not working, it creating drives/:drife_id/problems route and if accordingly changes are done with ProblemController then giving error as 'drife_id' column is not present

2021-03-15 17:01 UTC, rahulknojha approved these changes

2021-03-15 17:02 UTC, merged