added drives index, create and update method with testing
joshsoftware/OnCoT-API pull request #31
Opened 2021-03-19 05:31 UTC by atirabagwan

2021-03-19 06:24 UTC, somnath77 requested changes

2021-03-19 06:24 UTC, somnath77 commented on app/controllers/api/v1/admin/drives_controller.rb
> +end
Add an empty line at end of file

2021-03-19 06:24 UTC, somnath77 commented on app/controllers/api/v1/admin/drives_controller.rb
> +                        :duration)
No need to take duration from user, as we can calculate using start and end time

2021-03-19 06:24 UTC, somnath77 commented on app/controllers/api/v1/admin/drives_controller.rb
> +          drive = Drive.create(drive_params)
When you are directly creating drive, no need to save it again. Remove save or use new instead of create

2021-03-19 06:24 UTC, somnath77 commented on app/controllers/api/v1/admin/drives_controller.rb
> +          return unless drive.update(drive_params)
if update failed, render error

2021-03-19 06:24 UTC, somnath77 commented on spec/request/api/v1/admin/drives_spec.rb
> +end
New line at EOF. Applies to all rb files

2021-03-19 06:24 UTC, somnath77 commented on spec/support/request_helpers.rb
> +end
New line at end

2021-03-19 06:24 UTC, somnath77 commented on spec/request/api/v1/admin/drives_spec.rb
> +  # let(:organization) { create(:organization) }
You have to create data before testing cntrollers, organization, role, user, and then drive

2021-03-24 05:37 UTC, varungadde99 commented on spec/request/api/v1/admin/drives_spec.rb
> +    end
As per discussion with Rahul sir the test cases can be written in a better format
describe 'action#create'
 context 'positive senarios'
  it 'when valid params is passed'
 context 'negative senarios'
  it 'when invalid params is passed'

2021-03-24 05:41 UTC, varungadde99 commented on app/serializers/drive_serializer.rb
> +             :created_at, :updated_at
Remove :created_at and updated_at ..these are implicitly considered by RoR.
And mention only that fields which are necessary to be passed to frontend as json.

2021-03-24 09:45 UTC, somnath77 requested changes

2021-03-24 09:45 UTC, somnath77 commented on spec/request/api/v1/admin/drives_spec.rb
> +# frozen_string_literal: true
move drives_spec.rb into spec/controllers/api/v1/admin folder

2021-03-24 09:45 UTC, somnath77 commented on config/routes.rb
> +  end
why are you repeating code, just add line 38 at line 28. and delete lines 35 to 41

2021-03-24 09:45 UTC, somnath77 commented on spec/support/request_helpers.rb
>      def json(response)
no need of response param

2021-03-24 09:45 UTC, somnath77 commented on spec/request/api/v1/admin/drives_spec.rb
> +        patch :update, params: { id: Faker::Number }
You are testing for get method, but calling update here

2021-03-24 09:45 UTC, somnath77 commented on spec/request/api/v1/admin/drives_spec.rb
> +        expect(data['data']['drives'].count).to eq(Drive.count)
no need to pass response for json function , it is available for json method. Remove it and make changes in request_helper as well. Change this at all places

2021-03-25 05:59 UTC, somnath77 approved these changes

2021-03-25 06:07 UTC, rahulknojha commented on app/controllers/api/v1/admin/drives_controller.rb
> +          params.permit(:name, :description, :start_time, :end_time, :created_by_id, :updated_by_id, :organization_id,
will we get created by id or updated by id from params ?, I think we have done this in active admin as well. Not sure why its getting repeated again and again?

2021-03-25 06:07 UTC, rahulknojha commented on config/database.yml
> -
is this change needed for this feature ?

2021-03-25 06:07 UTC, rahulknojha commented on config/locales/en.yml
> +
is this changed needed for this feature ?

2021-03-25 06:10 UTC, rahulknojha requested changes

2021-03-25 06:10 UTC, rahulknojha commented on spec/controllers/api/v1/admin/candidates_controller_spec.rb
> +      expect(parsed_json_data['data']['time_left']).to be > 0
why did we changed this ?

2021-03-25 06:10 UTC, rahulknojha commented on spec/controllers/api/v1/admin/drives_spec.rb
> +    it 'checks drive count' do
better to frame like it `returns drives` do .. end

2021-03-25 06:10 UTC, rahulknojha commented on spec/spec_helper.rb
> +
is this change needed for this feature ?

2021-03-25 06:49 UTC, atirabagwan commented on app/controllers/api/v1/admin/drives_controller.rb
> +          params.permit(:name, :description, :start_time, :end_time, :created_by_id, :updated_by_id, :organization_id,
drive is not getting created without created by id and updated by id, currrently we need to pass these params once authorization applies  to the controller we can take this param from session

2021-03-25 06:50 UTC, atirabagwan commented on config/database.yml
> -
it was showing peer authentication error so deleted username

2021-03-25 06:51 UTC, atirabagwan commented on spec/controllers/api/v1/admin/candidates_controller_spec.rb
> +      expect(parsed_json_data['data']['time_left']).to be > 0
be.postitive? was showing error while unit testing

2021-03-25 06:53 UTC, atirabagwan commented on spec/spec_helper.rb
> +
removed

2021-03-25 06:54 UTC, atirabagwan commented on spec/controllers/api/v1/admin/drives_spec.rb
> +    it 'checks drive count' do
changed

2021-03-25 06:54 UTC, atirabagwan commented on config/locales/en.yml
> +
removed

2021-03-25 07:53 UTC, rahulknojha requested changes

2021-03-25 07:53 UTC, rahulknojha commented on app/controllers/api/v1/admin/drives_controller.rb
> +          params.permit(:name, :description, :start_time, :end_time, :created_by_id, :updated_by_id, :organization_id,
@atirabagwan  I think authorization is already there in development

2021-03-25 07:55 UTC, rahulknojha requested changes

2021-03-25 07:55 UTC, rahulknojha commented on config/database.yml
> -
where u have deleted username, I can see one blank line deleted

2021-04-05 05:08 UTC, rahulknojha approved these changes

2021-04-05 05:19 UTC, merged