Test-cases CRUD
joshsoftware/OnCoT-API pull request #32
Opened 2021-03-23 07:45 UTC by somnath77

```

1. Testcases CRUD added
2. Moved controller tests to controllers folder 
3. Testcase controller unit tests added

```

2021-03-23 10:51 UTC, rahulknojha requested changes

2021-03-23 10:51 UTC, rahulknojha commented on app/controllers/api/v1/admin/testcases_controller.rb
> +          testcases = TestCase.paginate(page: params[:page], per_page: 15)
should it be scoped by problem ?

2021-03-24 09:40 UTC, varungadde99 commented on spec/controllers/api/v1/admin/testcases_spec.rb
> +
Right now its okay. But as per discussed structure 
- Describe #action
  - Context - valid params
     - test cases
  - Context - invalid params
    - test cases
 this can be followed. Please check if such updation can be made.

2021-03-24 09:44 UTC, varungadde99 commented on app/controllers/api/v1/admin/testcases_controller.rb
> +            render_error(message: testcases.errors.messages, status: 400)
In en.yml file I cannot find the keywords for 
- testcases.errors.messages
Please check

2021-03-24 09:45 UTC, varungadde99 commented on config/locales/en.yml
>    success:
No entry of -> testcases.errors.messages which is being used in controller.

2021-03-24 09:48 UTC, varungadde99 commented on spec/controllers/api/v1/admin/candidates_controller_spec.rb
> +      expect(@drive.end_time - DateTime.now.localtime).to be.negative?
Please change this back to <0 and >0 
As rubocop -A changes them to .negative and .postitive.
But if you run the rspec over this code it will give errors.
To reproduce the same:
1. Run rpsec on current code with .neg and .pos attributes
2. Code will fail
3. Change the attributes to < 0 and > 0 and donot run rubocop -A.
4. Without running rubocop, run RSpec, it will pass.

2021-03-24 10:03 UTC, somnath77 commented on config/locales/en.yml
>    success:
`testcases.errors.messages` it gives in built error messages, not from en.yml

2021-03-24 10:04 UTC, samu80 commented on spec/controllers/api/v1/admin/testcases_spec.rb
> +      expect(response.body).to eq('Record not found')
line space missing after API call

2021-03-24 10:04 UTC, somnath77 commented on app/controllers/api/v1/admin/testcases_controller.rb
> +            render_error(message: testcases.errors.messages, status: 400)
These are in built messages

2021-03-24 10:04 UTC, somnath77 commented on app/controllers/api/v1/admin/testcases_controller.rb
> +          testcases = TestCase.paginate(page: params[:page], per_page: 15)
Changed for scope of a problem

2021-03-24 10:05 UTC, samu80 commented on app/controllers/api/v1/admin/testcases_controller.rb
> +          if testcase.save
we can write like 
if( testcase  =  TestCase.create(testcase_params)

2021-03-24 10:10 UTC, somnath77 commented on app/controllers/api/v1/admin/testcases_controller.rb
> +          if testcase.save
ok

2021-03-24 10:11 UTC, samu80 commented on spec/controllers/api/v1/admin/testcases_spec.rb
> +    it 'Creates the testcase' do
here you can write 
   context 'with valid params' do
       it 'creates testcase'
  context 'with invalid params' do
      it 'return error'  like this

2021-03-24 10:11 UTC, samu80 commented on spec/controllers/api/v1/admin/testcases_spec.rb
> +      expect(response.body).to eq('Record not found')
line space missing

2021-03-24 11:06 UTC, somnath77 commented on spec/controllers/api/v1/admin/testcases_spec.rb
> +
done

2021-03-24 11:06 UTC, somnath77 commented on spec/controllers/api/v1/admin/candidates_controller_spec.rb
> +      expect(@drive.end_time - DateTime.now.localtime).to be.negative?
Ok

2021-03-24 11:06 UTC, somnath77 commented on spec/controllers/api/v1/admin/testcases_spec.rb
> +      expect(response.body).to eq('Record not found')
Done

2021-03-25 03:59 UTC, varungadde99 submitted a review, later dismissed

2021-03-25 06:01 UTC, rahulknojha commented on app/controllers/api/v1/admin/testcases_controller.rb
> +          testcases = TestCase.where(problem_id: problem.id)
can we do like problem.test_cases, try using active record relations

2021-03-25 06:02 UTC, rahulknojha approved these changes

2021-03-25 11:03 UTC, somnath77 commented on app/controllers/api/v1/admin/testcases_controller.rb
> +          testcases = TestCase.where(problem_id: problem.id)
done

2021-03-25 11:31 UTC, varungadde99 submitted a review, later dismissed

2021-03-25 12:50 UTC, rahulknojha commented on .rubocop_todo.yml
> +    - 'spec/controllers/api/v1/admin/test_cases_spec.rb'
instead of adding one one file, you can exclude for entire spec folder

2021-03-25 12:52 UTC, rahulknojha commented on app/controllers/api/v1/admin/test_cases_controller.rb
> +          params['updated_by_id'] = current_user.id
instead of changing params here  this we can add this to action method like 

```
   TestCase.new(test_case_params.merge(created_by_id: current_user.id, updated_by_id: current_user.id))
```

2021-03-25 13:17 UTC, somnath77 commented on .rubocop_todo.yml
> +    - 'spec/controllers/api/v1/admin/test_cases_spec.rb'
done, excluded all .rb files int spec folder

2021-03-25 19:58 UTC, somnath77 commented on app/controllers/api/v1/admin/test_cases_controller.rb
> +          params['updated_by_id'] = current_user.id
yes, done

2021-03-26 12:13 UTC, varungadde99 approved these changes

2021-03-26 12:25 UTC, rahulknojha commented on spec/controllers/api/v1/admin/test_cases_spec.rb
> +      it 'shows all test_cases' do
`returns` would be better

2021-03-26 12:25 UTC, rahulknojha approved these changes

2021-03-26 12:36 UTC, merged