Submission api
joshsoftware/OnCoT-API pull request #38
Opened 2021-03-25 02:49 UTC by samu80

This API gives submission details
    • passed testcase
    • total testcases
    • submission_count remaining
    • marks obtained
when we pass source code and language id

2021-03-25 04:02 UTC, varungadde99 commented on app/controllers/submissions_controller.rb
> +        body = JSON.parse(response.body)
Please use the json parser already present:
-> body = json

2021-03-25 04:07 UTC, varungadde99 commented on app/controllers/submissions_controller.rb
> +        render_error(message: I18n.t('submission.not_created.message'))
Please add messages keywords in en.yml:
- submission.not_created.message
- submission.limit_exceed.message

2021-03-25 06:36 UTC, samu80 commented on app/controllers/submissions_controller.rb
> +        body = JSON.parse(response.body)
okay

2021-03-25 11:31 UTC, varungadde99 approved these changes

2021-03-25 11:53 UTC, rahulknojha commented on app/controllers/submissions_controller.rb
> +        sleep(1)
we can't go with this way, we have to find a solution for this.

2021-03-25 11:56 UTC, rahulknojha approved these changes

2021-03-25 11:56 UTC, rahulknojha commented on .rubocop_todo.yml
> +    - 'app/controllers/submissions_controller.rb'
you can't exclude, you have to fix this

2021-03-25 11:56 UTC, rahulknojha commented on spec/controllers/submission_spec.rb
> +          }.to_json)
most part of the stubbing is duplicate, find an way to iterate and remove duplicacy

2021-03-25 11:56 UTC, rahulknojha commented on spec/controllers/submission_spec.rb
> +        request.headers.merge!('CONTENT_TYPE' => 'application/json',
can we add this setup to rails helper file so that we do not need to merge headers in each request.

2021-03-25 11:58 UTC, samu80 commented on app/controllers/submissions_controller.rb
> +        sleep(1)
okay

2021-03-28 13:03 UTC, samu80 commented on .rubocop_todo.yml
> +    - 'app/controllers/submissions_controller.rb'
method length cannot be decreased, that much steps are essentail

2021-03-30 13:55 UTC, vaibhav8186 commented on spec/controllers/submission_spec.rb
> +        expect(response.body).to eq('submission limit exceeded')
@samu80   use local here.

2021-03-30 14:02 UTC, vaibhav8186 requested changes

2021-03-30 14:02 UTC, vaibhav8186 commented on .rubocop_todo.yml
> +    - 'app/controllers/submissions_controller.rb'
@samu80  You can separate some logical parts from this method.

2021-03-30 14:02 UTC, vaibhav8186 commented on app/controllers/submissions_controller.rb
> +        if body['status']['description'] == 'Accepted'
@samu80  use constant for 'Accepted'

2021-03-30 14:06 UTC, samu80 commented on .rubocop_todo.yml
> +    - 'app/controllers/submissions_controller.rb'
okay

2021-03-30 14:23 UTC, rahulknojha commented on .rubocop_todo.yml
> +    - 'app/controllers/submissions_controller.rb'
for spec we can exclude, but other than we can not.  @samu80 Don't make habit of excluding files, Please fix.

2021-03-31 06:58 UTC, samu80 commented on .rubocop_todo.yml
> +    - 'app/controllers/submissions_controller.rb'
okay

2021-04-01 04:30 UTC, closed without merging