Finish Button API
joshsoftware/OnCoT-API pull request #41
Opened 2021-03-31 12:07 UTC by samu80

This API updates test completed time when Finish Button is clicked 
also, In problem_controller (which is merged in development branch) one RSpec test was failing, that is also corrected

2021-04-01 11:14 UTC, vaibhav8186 requested changes

2021-04-01 11:14 UTC, vaibhav8186 commented on app/controllers/problems_controller.rb
> +      if (problem = Problem.find_by_id(drive_problem.problem_id))
@samu80   can we use association to find out problem objects.

2021-04-05 12:48 UTC, rahulknojha commented on db/migrate/20210331094703_add_score_to_drives_candidate.rb
> +    add_column :drives_candidates, :score, :integer
both migrations can be combined in one

2021-04-05 12:49 UTC, rahulknojha approved these changes

2021-04-05 14:17 UTC, rahulknojha approved these changes

2021-04-05 14:19 UTC, vaibhav8186 approved these changes

2021-04-05 14:28 UTC, merged

2021-04-05 14:28 UTC, samu80 commented
API merged