Drives results
joshsoftware/OnCoT-API pull request #43
Opened 2021-04-02 05:50 UTC by samu80

This API gives array of drives_candidate's
    - candidate_id
    - Maximum score
    - Test completed time

2021-04-05 13:03 UTC, rahulknojha requested changes

2021-04-05 13:03 UTC, rahulknojha commented on app/controllers/api/v1/drives_results_controller.rb
> +          drives_candidate.update(score: final_marks)
we should have reference in submission table for drive candidate, then this operation will become much easier, also it will help us to find drive of a submission

2021-04-05 13:03 UTC, rahulknojha commented on db/migrate/20210331094703_add_score_to_drives_candidate.rb
> +    add_column :drives_candidates, :score, :integer
again migration can be combined

2021-04-05 13:50 UTC, samu80 commented on app/controllers/api/v1/drives_results_controller.rb
> +    class DrivesResultsController < ApiController
okay

2021-04-07 14:53 UTC, somnath77 submitted a review, later dismissed

2021-04-08 03:42 UTC, vaibhav8186 requested changes

2021-04-08 03:42 UTC, vaibhav8186 commented on app/models/submission.rb
> +    p_id = problem_id
@samu80  no need to assign this variable.

2021-04-08 03:42 UTC, vaibhav8186 commented on spec/models/submission_spec.rb
> +    it ' updates score to database' do
extra space

2021-04-08 03:42 UTC, vaibhav8186 commented on spec/models/submission_spec.rb
> +      user = create(:user)
please check once you create an object then associated objects should create from the factory. So that we can avoid making too much test data in our specs.

2021-04-08 04:22 UTC, vaibhav8186 approved these changes

2021-04-08 04:46 UTC, rahulknojha commented on spec/models/submission_spec.rb
> +
ok for now, but it can be written in better way

2021-04-08 04:46 UTC, rahulknojha approved these changes

2021-04-08 04:48 UTC, merged