Code Execution API
joshsoftware/OnCoT-API pull request #46
Opened 2021-04-07 08:01 UTC by samu80

This API takes params (source_code, language_id) and resturns the output of the code

2021-04-07 08:33 UTC, somnath77 commented on app/controllers/api/v1/executions_controller.rb
> +        token = JSON.parse(response.body)['token']
you can write a support method to parse like we use in rspec

2021-04-07 09:14 UTC, somnath77 submitted a review, later dismissed

2021-04-07 11:52 UTC, varungadde99 submitted a review, later dismissed

2021-04-08 05:03 UTC, rahulknojha requested changes

2021-04-08 05:03 UTC, rahulknojha commented on app/controllers/api/v1/executions_controller.rb
> +        headers = { 'CONTENT_TYPE' => 'application/json', 'ACCEPT' => 'application/json' }
this is redundant, can't we add this in service itself ?

2021-04-08 05:03 UTC, rahulknojha commented on app/controllers/api/v1/executions_controller.rb
> +        token = JSON.parse(response.body)['token']
JSON.parse is also redundant, parse it in service and then return

2021-04-08 09:21 UTC, rahulknojha approved these changes

2021-04-08 09:21 UTC, merged

2021-04-08 09:22 UTC, samu80 commented
merged into development