Demo
joshsoftware/OnCoT-API pull request #51
Opened 2021-04-13 14:11 UTC by somnath77

1. Rules get api at candidate side
2. Changed drive time left api
3. Changed candidate test time left api
4. Changes in candidate results serializer

2021-04-14 08:32 UTC, samu80 commented on config/routes.rb
> +      get '/drives/:drive_id/rules', to: 'rules#index'
you can write like
resources :drives do
  resources :rules, only: [:index]
end

2021-04-14 15:23 UTC, somnath77 commented on config/routes.rb
> +      get '/drives/:drive_id/rules', to: 'rules#index'
it's becoming /drives/:drife_id/rules which is showing errors at frontend.

2021-04-15 12:52 UTC, samu80 approved these changes

2021-04-16 05:28 UTC, rahulknojha requested changes

2021-04-16 05:28 UTC, rahulknojha commented on app/controllers/api/v1/drives_controller.rb
> +          render json: { data: drive, candidate_id: drive_candidate.candidate_id, message: I18n.t('ok.message') }, status: 200
why we are no using serializer here ?, can we use render_success method ?

2021-04-16 05:28 UTC, rahulknojha commented on app/controllers/api/v1/submissions_controller.rb
>          if @drives_candidate.submissions.count < @submission_count
not sure why we are doing this ? we can always get submission time on run time by drives_candidate.submissions.count

2021-04-16 05:28 UTC, rahulknojha commented on config/initializers/devise_token_auth.rb
> +  config.max_number_of_devices = 100
why this change needed?

2021-04-16 05:28 UTC, rahulknojha commented on config/initializers/devise_token_auth.rb
> +  config.enable_standard_devise_support = false
why ?

2021-04-16 06:01 UTC, somnath77 commented on app/controllers/api/v1/drives_controller.rb
> +          render json: { data: drive, candidate_id: drive_candidate.candidate_id, message: I18n.t('ok.message') }, status: 200
candidate_id need to send with drive details which is not part of model, that's why didn't used serializer, If made changes in serializer, other controllers will show error

2021-04-16 06:01 UTC, somnath77 commented on config/initializers/devise_token_auth.rb
> +  config.max_number_of_devices = 100
Removed

2021-04-16 06:01 UTC, somnath77 commented on config/initializers/devise_token_auth.rb
> +  config.enable_standard_devise_support = false
Reverted change

2021-04-19 04:46 UTC, somnath77 commented on app/controllers/api/v1/drives_controller.rb
> +          render json: { data: drive, candidate_id: drive_candidate.candidate_id, message: I18n.t('ok.message') }, status: 200
used render_success method

2021-04-19 05:49 UTC, rahulknojha approved these changes

2021-04-19 05:53 UTC, merged