Result details API
joshsoftware/OnCoT-API pull request #52
Opened 2021-04-14 10:57 UTC by samu80

This API gives specific candidate results details 
    - passed testcases
    - failed testcases
    - code

2021-04-14 11:20 UTC, somnath77 approved these changes

2021-04-16 06:21 UTC, rahulknojha commented on app/controllers/api/v1/candidate_results_controller.rb
> +        end
why we are not using active record query.?

2021-04-16 06:21 UTC, rahulknojha requested changes

2021-04-16 06:21 UTC, rahulknojha commented on app/models/submission.rb
> +  }
indentation ?

2021-04-16 08:06 UTC, samu80 commented on app/models/submission.rb
> +  }
that line is autocorrected by rubocop

2021-04-16 11:58 UTC, rahulknojha commented on app/models/submission.rb
> +  scope :get_submissions, lambda { |drives_candidate_id, problem_id|
naming convention does not seems proper. what kind of submission we are trying to get is not clear

2021-04-19 05:58 UTC, rahulknojha submitted a review, later dismissed

2021-04-19 07:12 UTC, somnath77 approved these changes

2021-04-19 07:12 UTC, merged